# Encoding analysis on emotional socres

defaults:
  - roi_set: wholebrain_demo

encoder:
  name: encoding_emotion_score_cv_paper2020_featall_alpha${encoder.parameters.alpha}
  path: ./data/feature_encoders/${encoder.name}/${encoder.features.name}
  parameters:
    alpha: 100

  fmri:
    name: EmotionMovie_fmriprep_volume_native
    subjects:
      - name: Subject1
        paths:
          - ./data/fmri/paper2020/fmri_Subject1_for_tutorial.h5
    rois:
      - {name: Cortex,  select: Cortex = 1}
    label_key: stimulus_name

  features:
    name: amt/mean_score_concat
    paths:
      - ./data/features/${encoder.features.name}
    layers:
      - {name: category,  num: 0}
      - {name: dimension,  num: 0}

encoded_fmri:
  name: ${encoder.name}
  path: ./data/encoded_fmri/${encoded_fmri.name}/${encoded_fmri.features.name}
  parameters:
    average_sample: true

  encoder: ${encoder}
  fmri: ${encoder.fmri}
  features: ${encoder.features}

evaluation:
  fmri:
    rois: ${roi_set.rois}
      
# Cross-validation setting
cv:
  # Key used to split training and test samples for cross-validation (e.g., 'Run')
  key: Run
  
  # Values of the key splitting training and test samples in each cross-validation fold.
  # If omitted, leave-one-out cross-validation will be performed based on values of `cv.key`.
  folds:
    - {
      name: fold1,
      train: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61],
      test:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    }

  # In each CV fold, the training samples are removed if they have overlapping 
  # values of `cv exclusive key` with the test samples so that the training and
  # test samples do not have overlapping values for `cv exclusive key`.
  # Set `null` if not specified.
  exclusive_key: stimulus_name