# CV feature decoding

defaults:
  - roi_set: wholebrain_demo

decoder:
  name: decoding_emotion_score_dimension_cv_paper2020_voxel${decoder.parameters.select_voxel_num}_alpha${decoder.parameters.alpha}
  path: ./data/feature_decoders/${decoder.name}/${decoder.features.name}
  parameters:
    alpha: 100
    select_voxel_num: 500 
    chunk_axis: 1

  fmri:
    name: EmotionMovie_fmriprep_volume_native
    subjects:
      - name: Subject1
        paths:
          - ./data/fmri/paper2020/fmri_Subject1.h5
    rois: ${roi_set.rois}
    label_key: stimulus_name

  features:
    name: amt/mean_score_concat
    paths:
      - ./data/features/${decoder.features.name}
    layers:
      - category

decoded_feature:
  name: ${decoder.name}
  path: ./data/decoded_features/${decoded_feature.name}/${decoded_feature.features.name}
  parameters:
    average_sample: false

  decoder: ${decoder}

  fmri: 
    name: ${decoder.fmri.name}
    subjects: ${decoder.fmri.subjects}
    rois: ${decoder.fmri.rois}
    label_key: ${decoder.fmri.label_key}

  features: ${decoder.features}

# Cross-validation setting
cv:
  # Key used to split training and test samples for cross-validation (e.g., 'Run')
  key: Run

  # Values of the key splitting training and test samples in each cross-validation fold.
  # If omitted, leave-one-out cross-validation will be performed based on values of `cv.key`.
  folds:
    - {
      name: fold1,
      train: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61],
      test:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    }

  # In each CV fold, the training samples are removed if they have overlapping 
  # values of `cv exclusive key` with the test samples so that the training and
  # test samples do not have overlapping values for `cv exclusive key`.
  # Set `null` if not specified.
  #
  exclusive_key: stimulus_name
